name: ticket_checker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^7.0.1
  mobile_scanner: ^3.2.0
  shared_preferences: ^2.1.1

dev_dependencies:
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
